  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-web
    namespace: web
    annotations: 
      kubernetes.io/ingress.class: "nginx"
  spec:
    ingressClassName: nginx
    rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: tripviewer
                port:
                  number: 80
            path: /