kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-dev
subjects:
- kind: Group
  namespace: web
  name: 6bd8c56e-ed6b-4186-8381-f2da5e29ca03